export const languages = [
   {
      spanish: 'Español',
      english: 'Inglés',
      login: 'Iniciar sesión',
      register: 'Registrarse',
      Did_you_forget_your_password: '¿Olvidaste tu contraseña?',
      home: 'Inicio',
      dashboard: 'Panel',
      logout: 'Cerrar sesión',
      play_chess_online_and_improve_your_skills: 'Juega ajedrez online y mejora tus habilidades!',
      fast: 'Rapida',
      bullet: 'Bala',
      join_a_room: 'Unirse a una sala',
      loading_user_statistics: 'Cargando estadisticas del usuario',
      statistics_of: 'Estadisticas de',
      rating: 'Clasificación',
      total_games: 'Partidas totales',
      win: 'Victorias',
      lost: 'Derrotas',
      draw: 'Empates',
      win_streak: 'Racha ganadora',
      rank: 'Rango',
      game_history: 'Historial de partidas',
      Last_games_of: 'Ultimas partidas de',
      Language: 'Idioma',
      profile: 'Editar perfil',
      Challenge_a_match: 'Desafia una partida a',
      Loading_Players: 'Cargando jugadores',
      information: 'Información',
      You_have_sent_a_challenge: 'Has enviado un desafio',
      Challenge_rejected: 'Desafio rechazado',
      Challenge: 'Desafiar',
      message: 'Mensaje',
      Cancel: 'Cancelar',
      game_of: 'Partida de',
      has_challenged_you: 'te ha desafiado',
      Accept: 'Aceptar',
      email: 'Correo electronico',
      password: 'Contraseña',
      Forgot_your_password: '¿Olvidaste tu contraseña?',
      sign_in: 'Iniciar sesión',
      New_user: '¿Nuevo usuario?',
      Log_in_with_Google: 'Iniciar sesión con Google+',
      Sign_up: 'Registrarse',
      name: 'Nombre',
      lastName: 'Apellido',
      username: 'Usuario',
      confirm: 'Confirmar',
      Select_or_enter_a_country: 'seleccione o escriba un pais',
      sign_me_up: 'Registrarme',
      Sign_in_with : 'Iniciar sesión con',
      social_network: 'red social',
      welcome_to: 'Bienvenido',
      Email_address: 'Correo electronico',
      Enter_email: 'Introducir el correo electronico',
      We_will_send_you_an_email_to_change_your_password: 'Te enviaremos un correo para cambiar tu contraseña',
      send: 'Enviar',
      reset_password: 'Restablecer la contraseña',
      Range: 'Rango',
      Score: 'Puntaje',
      Offer_tables: 'Ofrecer tablas',
      Abandon: 'Abandonar',
      New_GAME: 'NUEVA PARTIDA',
      Choose_a_promotional_piece: 'Elige una pieza de promoción',
      login_welcome: 'Desafia a jugadores de todo el mundo. Mejora tus habilidades, escala en la clasificación y demuestra que eres el mejor.',
      settings: 'Configuración',
      authenticating: 'Autenticando',
      logging_in: 'Iniciando sesión',
   },
   {
    spanish: 'Spanish',
    english: 'English',
    login: 'Login',
    register: 'Register',
    did_you_forget_your_password: 'Did you forget your password?',
    home: 'Home',
    dashboard: 'Dashboard',
    logout: 'Logout',
    play_chess_online_and_improve_your_skills: 'Play chess online and improve your skills!',
    fast: 'Fast',
    bullet: 'Bullet',
    join_a_room: 'Join a room',
    loading_user_statistics: 'Loading user statistics:',
    statistics_of: 'Statistics of',
    rating: 'Rating',
    total_games: 'Total games',
    win: 'Win',
    lost: 'Lost',
    draw: 'Draw',
    win_streak: 'Win streak',
    rank: 'Rank',
    game_history: 'Games history',
    Last_games_of: 'Last games of',
    Language: 'Languaje',
    profile: 'Edit profile',
    Challenge_a_match: 'Challenge a match',
    Loading_Players: 'Loading Players',
    information: 'Information',
    You_have_sent_a_challenge: 'You have sent a challenge',
    Challenge_rejected: 'Challenge rejected',
    Challenge: 'Challenge',
    message: 'Message',
    Cancel: 'Cancel',
    game_of: 'Game of',
    has_challenged_you: 'has challenged you',
    Accept: 'Accept',
    email: 'Email',
    password: 'Password',
    Forgot_your_password: 'Forgot your password?',
    sign_in: 'Sign in',
    New_user: 'New user?',
    Log_in_with_Google: 'Log in with Google+',
    Sign_up: 'Sign up',
    name: 'Name',
    lastName: 'Lastname',
    username: 'User',
    confirm: 'Confirm',
    Select_or_enter_a_country: 'Select or enter a country',
    sign_me_up: 'Sign me up',
    Sign_in_with: 'Sign in with',
    social_network: 'social network',
    welcome_to: 'Welcome',
    Email_address: 'Email address',
    Enter_email: 'Enter email',
    We_will_send_you_an_email_to_change_your_password: 'We will send you an email to change your password',
    send: 'Send',
    reset_password: 'Reset password',
    Range: 'Range',
    Score: 'Score',
    Offer_tables: 'Offer tables',
    Abandon: 'Abandon',
    New_GAME: 'NEW GAME',
    Choose_a_promotional_piece: 'Choose a promotional piece',
    login_welcome: 'Challenge players from all over the world. Improve your skills, climb the leaderboard and prove that you are the best.',
    settings: 'Settings',
    authenticating: 'Authenticating',
    logging_in: 'Logging in...',
   }
];